### ISSUE TITLE
Percentage symbol causes hanging

### ISSUE THREAD

**Issue by wolfjagger** [carloskiki/pulldown-latex#16]
You can see this even on your test page https://carloskiki.github.io/pulldown-latex/. Enter "80%" and it will begin to hang as soon as you type the character.

(Love the crate; thank you!)

**Comment by carloskiki** [comment]
Looking into it!

**Comment by carloskiki** [comment]
I have fixed the issue and it is released in [v0.6.3](https://github.com/carloskiki/pulldown-latex/releases/tag/v0.6.3).

FYI: A percentage sign in LaTeX is a comment, if you want to see "80%" as output, you would need to type "80\\%" as input.

**Comment by wolfjagger** [comment]
Nice!

Yeah, I realized pretty quickly my mistake, but figured the hanging was unintended!
