### ISSUE TITLE
Panics for Grouping::Equation

### ISSUE THREAD

**Issue by photino** [carloskiki/pulldown-latex#18]
When I render a markdown content with math expressions, an error happens:

 ```
thread '<unnamed>' panicked at ~\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\pulldown-latex-0.6.3\src\mathml.rs:280:50:
not yet implemented
```

It is due to `Grouping::Equation { .. } => todo!()`. Should we ignore the parsing instead of panics for unimplemented features?

**Comment by carloskiki** [comment]
Implemented in `v0.7.1`

**Comment by photino** [comment]
It seems that the `0.7.1` version has not been published on crates-io.

**Comment by carloskiki** [comment]
Indeed, I forgot :)

It should be up now.
